{{- if .Values.insightzeppelin.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "alfresco-insight-zeppelin.fullName" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "alfresco-insight-zeppelin.fullName" . }}
            port: 
              number: {{ .Values.service.externalPort }}
{{- end }}
